language: go
go:
  - "1.11"
go_import_path: github.com/amitizle/twitter_lists_manager

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

deploy:
  - provider: script
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
